#!/usr/bin/env python3
#script used to great a file used by homography.py
#homography.py use 4 targets placed at the corner of a rectangle
#the arguments of the present script indicates what should be the pixel dimensions of 
#the rectangle and the margins (in pixel too) around it
import pickle
import argparse
parser = argparse.ArgumentParser(
   prog = 'homography_ref',
   description='creates a region of interest file used by \'homography\'. all measures are in pixels',
   epilog='Pierre Smars, 2023')
parser.add_argument('width', help='rectangle width')
parser.add_argument('height', help='rectangle height')
parser.add_argument('left', help='left margin')
parser.add_argument('right', help='right margin')
parser.add_argument('bottom', help='bottom margin')
parser.add_argument('top', help='top margin')
parser.add_argument('-o', '--output', metavar='outfile', help='file required by homography (default: homography_ref.pckl)', default='homography_ref.pckl')
args = parser.parse_args()
wl=int(args.width)
hl=int(args.height)
ml=int(args.left)
mr=int(args.right)
mb=int(args.bottom)
mt=int(args.top)
filename = args.output 
f = open(filename,'wb')
pickle.dump((wl,hl,ml,mr,mb,mt),f)
f.close()

