#!/usr/bin/env python3
import argparse
parser = argparse.ArgumentParser(
   prog = 'make_marker',
   description='create an aruco marker image file',
   epilog='Pierre Smars, 2023')
parser.add_argument('ref',metavar='val', help='reference number')
parser.add_argument('-s', '--size', metavar='val', help='pixel width of the output file (default: 300)', default=300)
args = parser.parse_args()
num=int(args.ref)
num=num%50
size=int(args.size)
import numpy as np
import cv2
import cv2.aruco as aruco
import matplotlib.pyplot as plt
dictionary = aruco.getPredefinedDictionary(aruco.DICT_4X4_50)
tag = cv2.aruco.generateImageMarker(dictionary,num,size)
cv2.imwrite("m"+str(num)+".png",tag)
plt.imshow(tag)
plt.show()

