#!/bin/env python3
import telnetlib
import argparse
parser = argparse.ArgumentParser(
   prog = 'run',
   description='launch the shaking table with the data already uploaded',
   epilog='Pierre Smars, 2023')
parser.add_argument('-H', '--host', default='servo', metavar='hostname', help='default: servo')
args = parser.parse_args()

host = args.host
tn = telnetlib.Telnet(host)
tn.read_until(b"> ",timeout=2)

tn.write(b"U\n")
msg=tn.read_until(b"> ",timeout=1)
tn.write(b"run\n")
msg=tn.read_until(b"> ",timeout=1)
tn.write(b"u\n")
msg=tn.read_until(b"> ",timeout=1)

tn.close()

