#!/bin/env python3
import argparse
parser = argparse.ArgumentParser(
   prog = 'transfer',
   description='transfer displacement data to the shaking table microcontroller',
   epilog='Pierre Smars, 2023')
parser.add_argument('filename', help='file containing the pulses')
parser.add_argument('-H', '--host', default='servo', metavar='hostname', help='default: servo')
args = parser.parse_args()
import telnetlib
host = args.host
tn = telnetlib.Telnet(host)
tn.read_until(b"> ",timeout=2)
tn.write(b"enable x\n")
msg=tn.read_until(b"> ",timeout=1)
f = open(args.filename,"r")
i = 0
for x in f:
    if (x[0] != "#"):
        i = i+1
        if (i>20000):
            print("Too many pulses!!")
            tn.close()
            exit()
        tn.write(x.encode('ascii'))
        msg=tn.read_until(b"> ",timeout=1)
        print(i)

tn.close()

